import pygame

INITIAL_PLACE = (0, 0)
DEFAULT_BACKGROUND_COLOR = (1, 90, 37)
PIXEL_PER_BLOCK = 30
MAT_ROW = 25
MAT_COL = 50
SCREEN_WIDTH = MAT_COL * PIXEL_PER_BLOCK
SCREEN_HEIGHT = MAT_ROW * PIXEL_PER_BLOCK

FONT_NAME = "Calibri"
OPENING_MESSAGE = "Welcome to the flag game' \nHave Fun!"
OPENING_FONT_SIZE = int(0.005 * SCREEN_WIDTH)
BLACK = (0, 0, 0)
OPENING_MESSAGE_COLOR = BLACK
OPENING_MESSAGE_LOCATION = (20, 0)

FLAG_LOCATION = (SCREEN_HEIGHT - 30, SCREEN_WIDTH - 40)
X_LOCATION = 0
Y_LOCATION = 0

SOLIDER_START_LOCATION = (0, 0)

GRASS_WIDTH = PIXEL_PER_BLOCK * 4
GRASS_HEIGHT = PIXEL_PER_BLOCK * 3
FLAG_WIDTH = PIXEL_PER_BLOCK * 4
FLAG_HEIGHT = PIXEL_PER_BLOCK * 3
SOLDIER_WIDTH = PIXEL_PER_BLOCK * 2
SOLDIER_HEIGHT = PIXEL_PER_BLOCK * 4
MINE_WIDTH = PIXEL_PER_BLOCK * 3
MINE_HEIGHT = PIXEL_PER_BLOCK * 1
