INITIAL_PLACE = (0, 0)
DEFAULT_BACKGROUND_COLOR = (138, 201, 38)
SCREEN_WIDTH=800
SCREEN_HEIGHT=600
FONT_NAME = "Calibri"
OPENING_MESSAGE = "Welcome to the flag game' \nHave Fun!"
OPENING_FONT_SIZE = int(0.005 * SCREEN_WIDTH)
BLACK = (0, 0, 0)
OPENING_MESSAGE_COLOR = BLACK
OPENING_MESSAGE_LOCATION =

