INITIAL_PLACE = (0, 0)
DEFAULT_BACKGROUND_COLOR = (138, 201, 38)
SCREEN_WIDTH=800
SCREEN_HEIGHT=600
FONT_NAME = "Calibri"
OPENING_MESSAGE = "Welcome to the flag game' \nHave Fun!"
LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)
LOSE_COLOR = BLACK
LOSE_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))
WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = (89, 89, 89)
WIN_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))